# Generated by Django 4.0.5 on 2022-07-11 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cursos', '0006_remove_curso_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='curso',
            name='autor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cursos.autor'),
        ),
    ]
